spring:
  application:
    name: todai
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://svc.sel4.cloudtype.app:32086/todai
    username: todai_admin
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: my-super-secret-key-for-jwt-encoding-1234567890
  access-token-expire-time: 3600000
  refresh-token-expire-time: 604800000
